### ISSUE TITLE
No module named 'rwf' and  module 'pandas' has no attribute 'Panel'

### ISSUE THREAD

**Issue by SteSeg** [luca-fiorito-11/sandy#247]
I tried to install SANDY via cloning the repository and running all the conda/pip lines quite fine up to the "on windows" lines, which I didn't do, of course. I am on a conda virtual environment (sandy-devel) as suggested. I met two problems: after having set the pythonpath I use ipython to try "import sandy" and I get the following error:

No module named 'rwf'

While, if I try the import sandy command on a VScode notebook (still in my sandy-devel environment), I get the following error:

AttributeError: module 'pandas' has no attribute 'Panel'

In any case I am stuck at the "import sandy" command.
I am on WSL2 (Ubuntu on Windows).

**Comment by Kladdy** [comment]
I got it working by cloning [this](https://github.com/makeclean/sandy/tree/nomorefortran) repository instead, using the nomorefortran branch (not develop branch).

I also had to downgrade scipy and pandas due to errors similar to yours, which I did with
```
pip install scipy==1.2
pip install pandas==0.24.2    
```
See the following pull request for more info: https://github.com/luca-fiorito-11/sandy/pull/239

**Comment by SteSeg** [comment]
Yes, I eventually got it working with the #239 PR too. Thank you!
